In [29]:
import requests
import pandas as pd
import defs

In [30]:
session = requests.Session()

In [31]:
instrument = 'EUR_USD'
count = 10
granularity = 'H1'

In [16]:
url = f'{defs.OANDA_URL}/instruments/{instrument}/candles'

In [32]:
url

'https://api-fxpractice.oanda.com/v3/accounts/101-001-39358426-001/instruments/EUR_USD/candles'

In [33]:
params = dict(
    count = count,
    granularity = granularity,
    price = 'MBA'
)

In [34]:
params

{'count': 10, 'granularity': 'H1', 'price': 'MBA'}

In [39]:
response = session.get(url, params=params, headers=defs.SECURE_HEADER)

In [40]:
response.status_code

200

In [41]:
data = response.json()
data

{'instrument': 'EUR_USD',
 'granularity': 'H1',
 'candles': [{'complete': True,
   'volume': 1647,
   'time': '2026-05-19T20:00:00.000000000Z',
   'bid': {'o': '1.16057', 'h': '1.16062', 'l': '1.16026', 'c': '1.16057'},
   'mid': {'o': '1.16065', 'h': '1.16069', 'l': '1.16035', 'c': '1.16066'},
   'ask': {'o': '1.16073', 'h': '1.16077', 'l': '1.16043', 'c': '1.16075'}},
  {'complete': True,
   'volume': 903,
   'time': '2026-05-19T21:00:00.000000000Z',
   'bid': {'o': '1.16005', 'h': '1.16076', 'l': '1.15984', 'c': '1.16069'},
   'mid': {'o': '1.16055', 'h': '1.16091', 'l': '1.16032', 'c': '1.16083'},
   'ask': {'o': '1.16105', 'h': '1.16112', 'l': '1.16054', 'c': '1.16097'}},
  {'complete': True,
   'volume': 882,
   'time': '2026-05-19T22:00:00.000000000Z',
   'bid': {'o': '1.16068', 'h': '1.16080', 'l': '1.16052', 'c': '1.16080'},
   'mid': {'o': '1.16082', 'h': '1.16088', 'l': '1.16062', 'c': '1.16088'},
   'ask': {'o': '1.16097', 'h': '1.16097', 'l': '1.16071', 'c': '1.16095'}},
  {'complete': True,
   'volume': 1368,
   'time': '2026-05-19T23:00:00.000000000Z',
   'bid': {'o': '1.16079', 'h': '1.16122', 'l': '1.16054', 'c': '1.16058'},
   'mid': {'o': '1.16087', 'h': '1.16130', 'l': '1.16062', 'c': '1.16067'},
   'ask': {'o': '1.16095', 'h': '1.16138', 'l': '1.16071', 'c': '1.16076'}},
  {'complete': True,
   'volume': 6077,
   'time': '2026-05-20T00:00:00.000000000Z',
   'bid': {'o': '1.16059', 'h': '1.16099', 'l': '1.16001', 'c': '1.16007'},
   'mid': {'o': '1.16068', 'h': '1.16106', 'l': '1.16009', 'c': '1.16014'},
   'ask': {'o': '1.16076', 'h': '1.16114', 'l': '1.16017', 'c': '1.16022'}},
  {'complete': True,
   'volume': 6929,
   'time': '2026-05-20T01:00:00.000000000Z',
   'bid': {'o': '1.16006', 'h': '1.16021', 'l': '1.15928', 'c': '1.15964'},
   'mid': {'o': '1.16013', 'h': '1.16030', 'l': '1.15936', 'c': '1.15972'},
   'ask': {'o': '1.16020', 'h': '1.16038', 'l': '1.15944', 'c': '1.15981'}},
  {'complete': True,
   'volume': 5135,
   'time': '2026-05-20T02:00:00.000000000Z',
   'bid': {'o': '1.15964', 'h': '1.16021', 'l': '1.15936', 'c': '1.15970'},
   'mid': {'o': '1.15973', 'h': '1.16030', 'l': '1.15944', 'c': '1.15978'},
   'ask': {'o': '1.15982', 'h': '1.16038', 'l': '1.15952', 'c': '1.15987'}},
  {'complete': True,
   'volume': 3733,
   'time': '2026-05-20T03:00:00.000000000Z',
   'bid': {'o': '1.15971', 'h': '1.16046', 'l': '1.15946', 'c': '1.16015'},
   'mid': {'o': '1.15979', 'h': '1.16054', 'l': '1.15954', 'c': '1.16023'},
   'ask': {'o': '1.15987', 'h': '1.16063', 'l': '1.15963', 'c': '1.16031'}},
  {'complete': True,
   'volume': 3601,
   'time': '2026-05-20T04:00:00.000000000Z',
   'bid': {'o': '1.16014', 'h': '1.16060', 'l': '1.15963', 'c': '1.15965'},
   'mid': {'o': '1.16022', 'h': '1.16068', 'l': '1.15970', 'c': '1.15973'},
   'ask': {'o': '1.16031', 'h': '1.16077', 'l': '1.15978', 'c': '1.15981'}},
  {'complete': False,
   'volume': 3680,
   'time': '2026-05-20T05:00:00.000000000Z',
   'bid': {'o': '1.15964', 'h': '1.16008', 'l': '1.15909', 'c': '1.15934'},
   'mid': {'o': '1.15972', 'h': '1.16016', 'l': '1.15918', 'c': '1.15942'},
   'ask': {'o': '1.15981', 'h': '1.16024', 'l': '1.15926', 'c': '1.15950'}}]}

In [42]:
data.keys()

dict_keys(['instrument', 'granularity', 'candles'])

In [43]:
len(data['candles'])

10

In [44]:
prices = ['mid', 'bid', 'ask']
ohlc = ['o', 'h', 'l', 'c']

In [45]:
our_data = []
for candle in data['candles']:
    if not candle['complete']:
        continue
    new_dict = {}
    new_dict['time'] = candle['time']
    new_dict['volume'] = candle['volume']
    for price in prices: 
        for o in ohlc:
            new_dict[f'{price}_{o}'] = candle[price][o]
    our_data.append(new_dict)

In [48]:
our_data[0]

{'time': '2026-05-19T20:00:00.000000000Z',
 'volume': 1647,
 'mid_o': '1.16065',
 'mid_h': '1.16069',
 'mid_l': '1.16035',
 'mid_c': '1.16066',
 'bid_o': '1.16057',
 'bid_h': '1.16062',
 'bid_l': '1.16026',
 'bid_c': '1.16057',
 'ask_o': '1.16073',
 'ask_h': '1.16077',
 'ask_l': '1.16043',
 'ask_c': '1.16075'}

In [49]:
candles_df = pd.DataFrame(our_data)
candles_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2026-05-19T20:00:00.000000000Z,1647,1.16065,1.16069,1.16035,1.16066,1.16057,1.16062,1.16026,1.16057,1.16073,1.16077,1.16043,1.16075
1,2026-05-19T21:00:00.000000000Z,903,1.16055,1.16091,1.16032,1.16083,1.16005,1.16076,1.15984,1.16069,1.16105,1.16112,1.16054,1.16097
2,2026-05-19T22:00:00.000000000Z,882,1.16082,1.16088,1.16062,1.16088,1.16068,1.16080,1.16052,1.16080,1.16097,1.16097,1.16071,1.16095
3,2026-05-19T23:00:00.000000000Z,1368,1.16087,1.16130,1.16062,1.16067,1.16079,1.16122,1.16054,1.16058,1.16095,1.16138,1.16071,1.16076
4,2026-05-20T00:00:00.000000000Z,6077,1.16068,1.16106,1.16009,1.16014,1.16059,1.16099,1.16001,1.16007,1.16076,1.16114,1.16017,1.16022
5,2026-05-20T01:00:00.000000000Z,6929,1.16013,1.16030,1.15936,1.15972,1.16006,1.16021,1.15928,1.15964,1.16020,1.16038,1.15944,1.15981
6,2026-05-20T02:00:00.000000000Z,5135,1.15973,1.16030,1.15944,1.15978,1.15964,1.16021,1.15936,1.15970,1.15982,1.16038,1.15952,1.15987
7,2026-05-20T03:00:00.000000000Z,3733,1.15979,1.16054,1.15954,1.16023,1.15971,1.16046,1.15946,1.16015,1.15987,1.16063,1.15963,1.16031
8,2026-05-20T04:00:00.000000000Z,3601,1.16022,1.16068,1.15970,1.15973,1.16014,1.16060,1.15963,1.15965,1.16031,1.16077,1.15978,1.15981

In [50]:
candles_df.to_pickle('EURUSD.pkl')
test_df = pd.read_pickle('EURUSD.pkl')
test_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2026-05-19T20:00:00.000000000Z,1647,1.16065,1.16069,1.16035,1.16066,1.16057,1.16062,1.16026,1.16057,1.16073,1.16077,1.16043,1.16075
1,2026-05-19T21:00:00.000000000Z,903,1.16055,1.16091,1.16032,1.16083,1.16005,1.16076,1.15984,1.16069,1.16105,1.16112,1.16054,1.16097
2,2026-05-19T22:00:00.000000000Z,882,1.16082,1.16088,1.16062,1.16088,1.16068,1.16080,1.16052,1.16080,1.16097,1.16097,1.16071,1.16095
3,2026-05-19T23:00:00.000000000Z,1368,1.16087,1.16130,1.16062,1.16067,1.16079,1.16122,1.16054,1.16058,1.16095,1.16138,1.16071,1.16076
4,2026-05-20T00:00:00.000000000Z,6077,1.16068,1.16106,1.16009,1.16014,1.16059,1.16099,1.16001,1.16007,1.16076,1.16114,1.16017,1.16022
5,2026-05-20T01:00:00.000000000Z,6929,1.16013,1.16030,1.15936,1.15972,1.16006,1.16021,1.15928,1.15964,1.16020,1.16038,1.15944,1.15981
6,2026-05-20T02:00:00.000000000Z,5135,1.15973,1.16030,1.15944,1.15978,1.15964,1.16021,1.15936,1.15970,1.15982,1.16038,1.15952,1.15987
7,2026-05-20T03:00:00.000000000Z,3733,1.15979,1.16054,1.15954,1.16023,1.15971,1.16046,1.15946,1.16015,1.15987,1.16063,1.15963,1.16031
8,2026-05-20T04:00:00.000000000Z,3601,1.16022,1.16068,1.15970,1.15973,1.16014,1.16060,1.15963,1.15965,1.16031,1.16077,1.15978,1.15981